<div id="lightbend-banner" class="lightbend-banner cloudstate full-width" data-category="OSS Lightbend Banner Impression" data-label="Cloudstate Banner Impression">
	<div class="wrapper">
		<div class="brand">
			<a class="oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Lightbend Logo - Cloudstate Banner" href="https://www.lightbend.com?r=oss-banner-cloudstate" target="_blank">
				<img class="lightbend-logo" src="$page.base$images/banner-logos/lightbend-reverse.svg" alt="Lightbend" title="Lightbend">
			</a>
		</div>
		<div class="nav">
			<a class="banner-btn oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Enhance your Cloudstate app with Lightbend [Button] - Cloudstate Banner" href="https://www.lightbend.com/cloudstate-by-lightbend?r=oss-banner-cloudstate" target="_blank">
				<span>Enhance your Cloudstate app with</span>
				<img class="lightbend-logo" src="$page.base$images/banner-logos/lightbend-reverse.svg" alt="Lightbend" title="Lightbend">
			</a>
			<div class="drop-down">
				<svg class="svg-chevon-circle-down" version="1.1" id="Chevron_circled_down" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 20 20" enable-background="new 0 0 20 20" xml:space="preserve">
					<path fill="#ffffff" d="M12.505,8.698L10,11L7.494,8.698c-0.198-0.196-0.518-0.196-0.718,0c-0.197,0.196-0.197,0.515,0,0.71l2.864,2.807
					c0.199,0.196,0.52,0.196,0.717,0l2.864-2.807c0.199-0.195,0.198-0.514,0-0.71C13.024,8.502,12.704,8.502,12.505,8.698z M10,0.4
					c-5.302,0-9.6,4.298-9.6,9.6c0,5.303,4.298,9.6,9.6,9.6s9.6-4.297,9.6-9.6C19.6,4.698,15.302,0.4,10,0.4z M10,18.354
					c-4.615,0-8.354-3.74-8.354-8.354c0-4.614,3.739-8.354,8.354-8.354c4.613,0,8.354,3.74,8.354,8.354
					C18.354,14.614,14.613,18.354,10,18.354z" />
				</svg>
				<div class="drop-down-content">
					<div class="lightbend-family">
						<a href="https://akka.io" class="akka oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Akka - Logo Tag Line - Cloudstate Banner">
							<img class="akka-full-color-logo" src="$page.base$images/banner-logos/akka-full-color.svg" alt="Akka by Lightbend" title="Akka by Lightbend">
						</a>
						<a href="https://cloudflow.io" class="cloudflow oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Cloudflow - Logo Tag Line - Cloudstate Banner">
							<img class="cloudflow-full-color-logo" src="$page.base$images/banner-logos/cloudflow-full-color.svg" alt="Cloudflow by Lightbend" title="Cloudflow by Lightbend">
						</a>
						<a href="https://www.lagomframework.com" class="lagom oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Lagom - Logo Tag Line - Cloudstate Banner">
							<img class="lagom-full-color-logo" src="$page.base$images/banner-logos/lagom-full-color.svg" alt="Lagom Framework by Lightbend" title="Lagom Framework by Lightbend">
						</a>
						<a href="https://www.playframework.com" class="play oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Play - Logo Tag Line - Cloudstate Banner">
							<img class="play-full-color-logo" src="$page.base$images/banner-logos/play-full-color.svg" alt="Play Framework by Lightbend" title="Play Framework by Lightbend">
						</a>
						<a href="https://www.scala-lang.org" class="scala oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Scala - Logo Tag Line - Cloudstate Banner">
							<img class="scala-full-color-logo" src="$page.base$images/banner-logos/scala-full-color.svg" alt="Scala by Lightbend" title="Scala by Lightbend">
						</a>
						<div class="cloudstate current">
							<img class="cloudstate-full-color-logo" src="$page.base$images/banner-logos/cloudstate-full-color.svg" alt="Cloudstate by Lightbend" title="Cloudstate by Lightbend">
							<span>From the creators of <strong>Cloudstate</strong>, get developer assistance and expert support from Lightbend.</span>
							<a class="oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Learn More [Button] - Cloudstate Banner" href="https://www.lightbend.com/cloudstate-by-lightbend?r=oss-banner-cloudstate" target="_blank">Learn More</a>
						</div>
					</div>
					<div class="title">The Lightbend Family</div>
				</div>      
			</div>
		</div>
	</div>
</div>
