// +build !ignore_autogenerated

/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraCredentials) DeepCopyInto(out *CassandraCredentials) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraCredentials.
func (in *CassandraCredentials) DeepCopy() *CassandraCredentials {
	if in == nil {
		return nil
	}
	out := new(CassandraCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraStore) DeepCopyInto(out *CassandraStore) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(CassandraCredentials)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraStore.
func (in *CassandraStore) DeepCopy() *CassandraStore {
	if in == nil {
		return nil
	}
	out := new(CassandraStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudstateCondition) DeepCopyInto(out *CloudstateCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudstateCondition.
func (in *CloudstateCondition) DeepCopy() *CloudstateCondition {
	if in == nil {
		return nil
	}
	out := new(CloudstateCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpCredentials) DeepCopyInto(out *GcpCredentials) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpCredentials.
func (in *GcpCredentials) DeepCopy() *GcpCredentials {
	if in == nil {
		return nil
	}
	out := new(GcpCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleCloudSQLPostgresStorage) DeepCopyInto(out *GoogleCloudSQLPostgresStorage) {
	*out = *in
	out.Capacity = in.Capacity.DeepCopy()
	out.AutomaticIncreaseLimit = in.AutomaticIncreaseLimit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleCloudSQLPostgresStorage.
func (in *GoogleCloudSQLPostgresStorage) DeepCopy() *GoogleCloudSQLPostgresStorage {
	if in == nil {
		return nil
	}
	out := new(GoogleCloudSQLPostgresStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleCloudSQLPostgresStore) DeepCopyInto(out *GoogleCloudSQLPostgresStore) {
	*out = *in
	out.Memory = in.Memory.DeepCopy()
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleCloudSQLPostgresStore.
func (in *GoogleCloudSQLPostgresStore) DeepCopy() *GoogleCloudSQLPostgresStore {
	if in == nil {
		return nil
	}
	out := new(GoogleCloudSQLPostgresStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleCloudSQLPostgresStoreStatus) DeepCopyInto(out *GoogleCloudSQLPostgresStoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleCloudSQLPostgresStoreStatus.
func (in *GoogleCloudSQLPostgresStoreStatus) DeepCopy() *GoogleCloudSQLPostgresStoreStatus {
	if in == nil {
		return nil
	}
	out := new(GoogleCloudSQLPostgresStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresCredentials) DeepCopyInto(out *PostgresCredentials) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresCredentials.
func (in *PostgresCredentials) DeepCopy() *PostgresCredentials {
	if in == nil {
		return nil
	}
	out := new(PostgresCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresStore) DeepCopyInto(out *PostgresStore) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(PostgresCredentials)
		(*in).DeepCopyInto(*out)
	}
	if in.GoogleCloudSQL != nil {
		in, out := &in.GoogleCloudSQL, &out.GoogleCloudSQL
		*out = new(GoogleCloudSQLPostgresStore)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresStore.
func (in *PostgresStore) DeepCopy() *PostgresStore {
	if in == nil {
		return nil
	}
	out := new(PostgresStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresStoreStatus) DeepCopyInto(out *PostgresStoreStatus) {
	*out = *in
	if in.GoogleCloudSQL != nil {
		in, out := &in.GoogleCloudSQL, &out.GoogleCloudSQL
		*out = new(GoogleCloudSQLPostgresStoreStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresStoreStatus.
func (in *PostgresStoreStatus) DeepCopy() *PostgresStoreStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpannerStore) DeepCopyInto(out *SpannerStore) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpannerStore.
func (in *SpannerStore) DeepCopy() *SpannerStore {
	if in == nil {
		return nil
	}
	out := new(SpannerStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulService) DeepCopyInto(out *StatefulService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulService.
func (in *StatefulService) DeepCopy() *StatefulService {
	if in == nil {
		return nil
	}
	out := new(StatefulService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatefulService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulServiceList) DeepCopyInto(out *StatefulServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StatefulService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulServiceList.
func (in *StatefulServiceList) DeepCopy() *StatefulServiceList {
	if in == nil {
		return nil
	}
	out := new(StatefulServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatefulServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulServiceSpec) DeepCopyInto(out *StatefulServiceSpec) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.StoreConfig != nil {
		in, out := &in.StoreConfig, &out.StoreConfig
		*out = new(StatefulServiceStoreConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulServiceSpec.
func (in *StatefulServiceSpec) DeepCopy() *StatefulServiceSpec {
	if in == nil {
		return nil
	}
	out := new(StatefulServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulServiceStatus) DeepCopyInto(out *StatefulServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]CloudstateCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulServiceStatus.
func (in *StatefulServiceStatus) DeepCopy() *StatefulServiceStatus {
	if in == nil {
		return nil
	}
	out := new(StatefulServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulServiceStoreConfig) DeepCopyInto(out *StatefulServiceStoreConfig) {
	*out = *in
	out.StatefulStore = in.StatefulStore
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulServiceStoreConfig.
func (in *StatefulServiceStoreConfig) DeepCopy() *StatefulServiceStoreConfig {
	if in == nil {
		return nil
	}
	out := new(StatefulServiceStoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulStore) DeepCopyInto(out *StatefulStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulStore.
func (in *StatefulStore) DeepCopy() *StatefulStore {
	if in == nil {
		return nil
	}
	out := new(StatefulStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatefulStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulStoreList) DeepCopyInto(out *StatefulStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StatefulStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulStoreList.
func (in *StatefulStoreList) DeepCopy() *StatefulStoreList {
	if in == nil {
		return nil
	}
	out := new(StatefulStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatefulStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulStoreSpec) DeepCopyInto(out *StatefulStoreSpec) {
	*out = *in
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresStore)
		(*in).DeepCopyInto(*out)
	}
	if in.Spanner != nil {
		in, out := &in.Spanner, &out.Spanner
		*out = new(SpannerStore)
		(*in).DeepCopyInto(*out)
	}
	if in.Cassandra != nil {
		in, out := &in.Cassandra, &out.Cassandra
		*out = new(CassandraStore)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulStoreSpec.
func (in *StatefulStoreSpec) DeepCopy() *StatefulStoreSpec {
	if in == nil {
		return nil
	}
	out := new(StatefulStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulStoreStatus) DeepCopyInto(out *StatefulStoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]CloudstateCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresStoreStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulStoreStatus.
func (in *StatefulStoreStatus) DeepCopy() *StatefulStoreStatus {
	if in == nil {
		return nil
	}
	out := new(StatefulStoreStatus)
	in.DeepCopyInto(out)
	return out
}
