# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/cloudstate.io_statefulstores.yaml
- bases/cloudstate.io_statefulservices.yaml
- bases/cloudstate.io_routes.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_statefulstores.yaml
#- patches/webhook_in_statefulservices.yaml
#- patches/webhook_in_routes.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_statefulstores.yaml
#- patches/cainjection_in_statefulservices.yaml
#- patches/cainjection_in_routes.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

patchesJson6902:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: statefulservices.cloudstate.io
  path: patches/fix-container-port-protocol-patch.yaml

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
