apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: statefulservices.cloudstate.io
spec:
  group: cloudstate.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: statefulservices
    singular: statefulservice
    kind: StatefulService
  subresources:
    status: {}
