# Deployment spec for a store. A store is a logical abstraction over a database
# deployment, and captures how to deploy and connect to that database. Multiple
# StatefulServices's would use a single store.
apiVersion: cloudstate.io/v1alpha1
kind: StatefulStore
metadata:
  name: cassandra
spec:

  # This is a Cassandra deployment, so supply configuration for Cassandra.
  cassandra:

    # The host name of the Cassandra service to connect to.
    service: cassandra-cassandra-0.cassandra-cassandra-svc.cassandra.svc.cluster.local
