# Deployment spec for a store. A store is a logical abstraction over a database
# deployment, and captures how to deploy and connect to that database. Multiple
# StatefulService's would use a single store.
apiVersion: cloudstate.io/v1alpha1
kind: StatefulStore
metadata:
  name: inmemory
  labels:
      foo: bar
spec:
  inMemory: {}

