# Deployment spec for a journal. A journal is a logical abstraction over a database
# deployment, and captures how to deploy and connect to that database. Multiple
# StatefulService's would use a single journal.
apiVersion: cloudstate.io/v1alpha1
kind: Journal
metadata:
  name: inmemory
spec:

  # The type of Journal - valid values would come from an enum of supported databases.
  # This is the InMemory journal, which obviously should not be used in production.
  type: InMemory

