# Deployment spec for our shopping cart event sourced function
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: shopping-cart
spec:

  # Journal configuration
  journal:

    # Name of a deployed Journal to use.
    name: cassandra

    # Journal specific configuration
    config:

      # Since the journal is a Cassandra journal, we need to specify the keyspace to use.
      keyspace: shoppingcart

  containers:
    - image: cloudstateio/js-shopping-cart:latest
