# Deployment spec for our shopping cart event sourced function
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: shopping-cart
spec:

  # Datastore configuration
  storeConfig:
    statefulStore:
        # Name of a deployed Datastore to use.
        name: inmemory

  containers:
    - image: cloudstateio/samples-js-shopping-cart:latest
      name: user-function
