# Deployment spec for a store. A store is a logical abstraction over a database
# deployment, and captures how to deploy and connect to that database. Multiple
# StatefulServices's would use a single store.
apiVersion: cloudstate.io/v1alpha1
kind: StatefulStore
metadata:
  name: postgres
spec:

  # Configuration for a postgres store
  type: Postgres

    # The name of the unmanaged Postgres service to connect to.
    host: postgresql-postgresql-svc.postgresql.svc.cluster.local

    # The credentials for connecting to Postgres
    credentials:
      
      # The secret to consume the credentials from
      secret:
        name: postgres-shopping-cart
      
      # By default, the database, username and password will be read from fields in the
      # secret with the keys database, username and password respectively. If your
      # secret uses different keys, eg, db, user and pass, they can be customized 
      # as shown below:
    
      # databaseKey = db
      # usernameKey = user
      # passwordKey = pass

