apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  replicas: &replicas 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: generator
        image: gcr.io/stateserv/js-shopping-cart-load-generator:latest

        env:
        - name: NUM_USERS
          value: "100"
        - name: REQUEST_RATE_PER_S
          value: "200"
        - name: RAMP_UP_S
          value: "20"
        - name: SHOPPING_CART_SERVICE
          value: "shopping-cart.default.svc.cluster.local"
        - name: SHOPPING_CART_SERVICE_PORT
          value: "80"
        - name: READ_WRITE_REQUEST_RATIO
          value: "1.0"
        - name: MAX_RESPONSE_LAG_MS
          value: "2000"
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx128m"

        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 0.25
            memory: 256Mi
