apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cloudstate-operator
subjects:
- kind: ServiceAccount
  name: cloudstate-operator
  namespace: cloudstate
roleRef:
  kind: ClusterRole
  name: cloudstate-operator-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cloudstate-operator
subjects:
- kind: ServiceAccount
  name: cloudstate-operator
roleRef:
  kind: Role
  name: cloudstate-operator-role
  apiGroup: rbac.authorization.k8s.io
