apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.yaml: |
    noStore:
      image: cloudstateio/cloudstate-proxy-no-store:latest
    inMemory:
      image: cloudstateio/cloudstate-proxy-in-memory:latest
    postgres:
      image: cloudstateio/cloudstate-proxy-postgres:latest
    cassandra:
      image: cloudstateio/cloudstate-proxy-cassandra:latest
    # sidecarMetrics:
    #  port: 9099