apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: cloudstate-operator
    app.kubernetes.io/part-of: cloudstatemachine
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app: cloudstate-operator
        manager.cloudstate.io/ignore: "true"
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: cloudstateio/cloudstate-operator:latest
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: cloudstate-config
            optional: true
