# Deployment spec for our shopping cart event sourced function
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: shopping-cart
spec:

  # Datastore configuration
  datastore:

    # Name of a deployed Datastore to use.
    name: cassandra

    # Datastore specific configuration
    config:

      # Since the datastore is a Cassandra datastore, we need to specify the keyspace to use.
      keyspace: shoppingcart

  containers:
    - image: gcr.io/stateserv/js-shopping-cart:latest
