= Conflict-free Replicated Data Types

This page documents how to implement Cloudstate CRDT entities in Java. For information on what Cloudstate CRDT entities are, please read the general xref:concepts:crdts.adoc[Conflict-free Replicated Data Type] documentation first.

A CRDT can be created by annotating it with the link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/CrdtEntity.html[`@CrdtEntity`] annotation.

[source,java]
----
include::example$docs/user/crdt/ShoppingCartEntity.java[tag=entity-class]
----

== Accessing and creating an entity's CRDT

Each CRDT entity manages one root CRDT. That CRDT will either be supplied to the entity by the proxy when it is started, or, if no CRDT exists for the entity when it is started, it can be created by the entity using a link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/CrdtFactory.html[`CrdtFactory`] extending context.

There are multiple ways that a CRDT entity may access its CRDT. It may have the CRDT injected directly into its constructor or a command handler - the value can be wrapped in an `Optional` to distinguish between entities that have been created and CRDTs that have not yet been created. If not wrapped in `Optional`, the CRDT will be created automatically, according to its type. The CRDT can also be read from any link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/CrdtContext.html[`CrdtContext`] via the link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/CrdtContext.html#state-java.lang.Class-[`state`] method.

An entity's CRDT can be created from the entity's constructor using the `CrdtFactory` methods on link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/CrdtCreationContext.html[`CrdtCreationContext`], or using the same methods in a command handler using the link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/CommandContext.html[`CommandContext`]. Note that the CRDT may only be created once, and only if it hasn't been provided by the CloudState proxy already. Any attempt to create a CRDT when one already exists will throw an `IllegalStateException`.

For most use cases, simply injecting the CRDT directly into the constructor, and storing in a local field, will be the most convenient and straightforward method of using a CRDT. In our shopping cart example, we're going to use an link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/LWWRegisterMap.html[`LWWRegisterMap`], this shows how it may be injected:

[source,java]
----
include::example$docs/user/crdt/ShoppingCartEntity.java[tag=creation]
----

In addition to the CRDT, the constructor may accept a link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/CrdtCreationContext.html[`CrdtCreationContext`].

== Handling commands

Command handlers can be declared by annotating a method with link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/CommandHandler.html[`@CommandHandler`]. They take a context class of type link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/CommandContext.html[`CommandContext`].

By default, the name of the command that the method handles will be the name of the method with the first letter capitalized. So, a method called `getCart` will handle gRPC service call command named `GetCart`. This can be overridden by setting the `name` parameter on the `@CommandHandler` annotation.

The command handler also can take the gRPC service call input type as a parameter, to receive the command message. This is optional, sometimes it's not needed. For example, our `GetCart` service call doesn't need any information from the message, since it's just returning the current state as is. Meanwhile, the `AddItem` service call does need information from the message, since it needs to know the product id, description and quantity to add to the cart.

The return type of the command handler must be the output type for the gRPC service call, this will be sent as the reply.

The following shows the implementation of the `GetCart` command handler. This command handler is a read-only command handler, it doesn't update the CRDT, it just returns some state:

[source,java]
----
include::example$docs/user/crdt/ShoppingCartEntity.java[tag=get-cart]
----

== Updating a CRDT

Due to CloudState's xref:concepts:crdts.adoc#approach-to-crdts-in-cloudstate[take in turns approach], CRDTs may only be updated in command handlers and <<Responding to stream cancellation,stream cancellation callbacks>>.

Here's a command handler for the `AddItem` command that adds the item to the shopping cart:

[source,java]
----
include::example$docs/user/crdt/ShoppingCartEntity.java[tag=add-item]
----

== Deleting a CRDT

A CRDT can be deleted by invoking link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/CommandContext.html#delete--[`CommandContext.delete`]. Once a CRDT is deleted, the entity will be shut down, and all subsequent commands for the entity will be rejected.

Caution should be taken when deleting CRDTs - the Reference Implementation of the proxy needs to maintain tombstones for each CRDT deleted, so over time, if many CRDTs are created and deleted, this will result in not just running out of memory, but increased network usage as the tombstones still need to be gossipped through the cluster for replication.

== Streamed command handlers

Streamed commands can be used to receive and publish updates to the state. If a gRPC service call has a streamed result type, the handler for that call can accept a link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/StreamedCommandContext.html[`StreamedCommandContext`], and use that to register callbacks.

=== Responding to changes

If the command handler wishes to publish changes to the stream it can register a callback with link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/StreamedCommandContext.html#onChange-java.util.function.Function-[`onChange`], which will be invoked every time the CRDT changes.

The callback is then able to return a message to be sent to the client (or empty, if it wishes to send no message in response to that particular change). The callback may not modify the CRDT itself, but it may emit effects that may modify the CRDT.

If the shopping cart service had a `WatchCart` call, like this:

[source,protobuf]
----
rpc WatchCart(GetShoppingCart) returns (stream Cart);
----

that could be implemented like this:

[source,java]
----
include::example$docs/user/crdt/ShoppingCartEntity.java[tag=watch-cart]
----

=== Ending the stream

The `onChange` callback can end the stream by invoking link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/SubscriptionContext.html#endStream--[`endStream`] on the link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/SubscriptionContext.html[`SubscriptionContext`] it is passed. If it does this, it will not receive an `onCancel` callback.

=== Responding to stream cancellation

A streamed command handler may also register an link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/StreamedCommandContext.html#onCancel-java.util.function.Consumer-[`onCancel`] callback to be notified when the stream is cancelled. The cancellation callback handler may update the CRDT. This is useful if the CRDT is being used to track connections, for example, when using link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/Vote.html[`Vote`] CRDTs to track a user's online status.

== Types of CRDTs

The Cloudstate Java support library offers Java classes for each of the xref:concepts:crdts.adoc#crdts-available-in-cloudstate[CRDTs available in Cloudstate].

=== Counters and flags

link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/GCounter.html[`GCounter`], link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/PNCounter.html[`PNCounter`] and link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/Flag.html[`Flag`] are available, offering operations relevant to each CRDT.

=== Vote

link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/Vote.html[`Vote`] is available for the Vote CRDT. The Vote CRDT allows updating the current node's vote using the link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/Vote.html#vote-boolean-[`vote`] method, the current nodes vote can be queried using the link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/Vote.html#getSelfVote--[`getSelfVote`] method.

For determining the result of a vote, link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/Vote.html#getVoters--[`getVoters`] and link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/Vote.html#getVotesFor--[`getVotesFor`] can be used to check the total number of nodes, and the number of nodes that have voted for the condition, respectively. In addition, convenience methods are provided for common vote decision approaches, link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/Vote.html#isAtLeastOne--[`isAtLeastOne`] returns true if there is at least one voter for the condition, link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/Vote.html#isMajority--[`isMajority`] returns true if the number of votes for is more than half the number of voters, and link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/Vote.html#isUnanimous--[`isUnanimous`] returns true if the number of votes for equals the number of voters.

=== Registers

link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/LWWRegister.html[`LWWRegister`] provides the LWWRegister CRDT. It can be interacted with using the link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/LWWRegister.html#set-T-[`set`] and link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/LWWRegister.html#get--[`get`] methods. If you wish to use a custom clock, you can use the link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/LWWRegister.html#set-T-io.cloudstate.javasupport.crdt.LWWRegister.Clock-long-[`set`] overload that allows passing a custom clock and custom clock value.

[IMPORTANT]
====
Direct mutations to link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/LWWRegister.html[`LWWRegister`] and link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/LWWRegisterMap.html[`LWWRegisterMap`] values will not be replicated to other nodes, only mutations triggered through using the link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/LWWRegister.html#set-T-[`set`] and link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/LWWRegisterMap.html#put-K-V-[`put`] methods will be replicated. Hence, the following update will not be replicated:

[source,java]
----
myLwwRegister.get().setSomeField("foo");
----

This update however will be replicated:

[source,java]
----
MyValue myValue = myLwwRegister.get();
myValue.setSomeField("foo");
myLwwRegister.set(myValue);
----

In general, we recommend that these values be immutable, as this will prevent accidentally mutating without realising the update won't be applied. If using protobufs as values, this will be straightforward, since compiled protobuf classes are immutable.
====

=== Sets and Maps

Cloudstate Java support provides link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/GSet.html[`GSet`] and link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/ORSet.html[`ORSet`] that implement the `java.util.Set` interface, and link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/ORMap.html[`ORMap`] that implements the `java.util.Map`. However, not all operations are implemented - `GSet` doesn't support any removal operations, and `ORMap` does not support any operations that would replace an existing value in the map.

To insert a value into an `ORMap`, you should use the link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/ORMap.html#getOrCreate-K-java.util.function.Function-[`getOrCreate`] method. The passed in callback will give you a link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/CrdtFactory.html[`CrdtFactory`] that you can use to create the CRDT value that you wish to use.

[IMPORTANT]
====
With all maps and sets, map keys and set values must be immutable. Cloudstate ignores the individual mutation of the key or value (not replicated to other nodes). Furthermore, their serialized form must be stable.
The Cloudstate proxy uses the serialized form of the values to track changes in the set or map. If the same value serializes to two different sets of bytes on different occasions, they will be treated as different elements in the set or map.

This is particularly relevant when using protobufs. The ordering of map entries in a serialized protobuf is undefined, and very often will be different for two equal maps. Hence, maps should never be used as keys in `ORMap` or as values in `GSet`, `ORSet`.
For the rest of the protobuf specification, while no guarantees are made on the stability by the protobuf specification itself, the Java libraries do produce stable orderings of fields and stable output of non-map values. Care should be taken when changing the protobuf structure. Many changes, that are backwards compatible from a protobuf standpoint, do not necessarily translate into stable serializations.

If using JSON serialization, it is recommended that you explicitly define the field ordering using Jackson's `@JsonPropertyOrder` annotation, and as with protobufs, never use `Map` or `Set` in your JSON objects since the ordering of those is not stable.
====

Some wrapper classes are also provided for ORMap. These provide more convenient APIs for working with values of particular CRDT types. They are:

link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/LWWRegisterMap.html[`LWWRegisterMap`]::
A map of LWWRegister values. This exposes the LWWRegister values as values directly in the map.

link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/PNCounterMap.html[`PNCounterMap`]::
A map of PNCounter values. This exposes the current value of the PNCounters directly as values in the map, and offers link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/PNCounterMap.html#increment-java.lang.Object-long-[`increment`] and link:{attachmentsdir}/api/io/cloudstate/javasupport/crdt/PNCounterMap.html#decrement-java.lang.Object-long-[`decrement`] methods to update the values.

== Registering the entity

Once you've created your entity, you can register it with the link:{attachmentsdir}/api/io/cloudstate/javasupport/CloudState.html[`CloudState`] server, by invoking the link:++api/io/cloudstate/javasupport/CloudState.html#registerEventSourcedEntity-java.lang.Class-com.google.protobuf.Descriptors.ServiceDescriptor-com.google.protobuf.Descriptors.FileDescriptor...-++[`registerCrdtEntity`] method.
In addition to passing your entity class and service descriptor, if you use protobuf for serialization and any protobuf message definitions are missing from your service descriptor (they are not declared directly in the file, nor as dependencies), then you'll need to pass those protobuf descriptors as well.

[source,java]
----
include::example$docs/user/crdt/ShoppingCartEntity.java[tag=register]
----
