// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shoppingcart/shoppingcart.proto

package shoppingcart

import (
	_ "cloudstate.io/gosupport/cloudstate/protocol"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddLineItem struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             int32    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddLineItem) Reset()         { *m = AddLineItem{} }
func (m *AddLineItem) String() string { return proto.CompactTextString(m) }
func (*AddLineItem) ProtoMessage()    {}
func (*AddLineItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_230c614558c2d7f8, []int{0}
}

func (m *AddLineItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddLineItem.Unmarshal(m, b)
}
func (m *AddLineItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddLineItem.Marshal(b, m, deterministic)
}
func (m *AddLineItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddLineItem.Merge(m, src)
}
func (m *AddLineItem) XXX_Size() int {
	return xxx_messageInfo_AddLineItem.Size(m)
}
func (m *AddLineItem) XXX_DiscardUnknown() {
	xxx_messageInfo_AddLineItem.DiscardUnknown(m)
}

var xxx_messageInfo_AddLineItem proto.InternalMessageInfo

func (m *AddLineItem) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddLineItem) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *AddLineItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddLineItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type RemoveLineItem struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveLineItem) Reset()         { *m = RemoveLineItem{} }
func (m *RemoveLineItem) String() string { return proto.CompactTextString(m) }
func (*RemoveLineItem) ProtoMessage()    {}
func (*RemoveLineItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_230c614558c2d7f8, []int{1}
}

func (m *RemoveLineItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveLineItem.Unmarshal(m, b)
}
func (m *RemoveLineItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveLineItem.Marshal(b, m, deterministic)
}
func (m *RemoveLineItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveLineItem.Merge(m, src)
}
func (m *RemoveLineItem) XXX_Size() int {
	return xxx_messageInfo_RemoveLineItem.Size(m)
}
func (m *RemoveLineItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveLineItem.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveLineItem proto.InternalMessageInfo

func (m *RemoveLineItem) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RemoveLineItem) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type GetShoppingCart struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShoppingCart) Reset()         { *m = GetShoppingCart{} }
func (m *GetShoppingCart) String() string { return proto.CompactTextString(m) }
func (*GetShoppingCart) ProtoMessage()    {}
func (*GetShoppingCart) Descriptor() ([]byte, []int) {
	return fileDescriptor_230c614558c2d7f8, []int{2}
}

func (m *GetShoppingCart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShoppingCart.Unmarshal(m, b)
}
func (m *GetShoppingCart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShoppingCart.Marshal(b, m, deterministic)
}
func (m *GetShoppingCart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShoppingCart.Merge(m, src)
}
func (m *GetShoppingCart) XXX_Size() int {
	return xxx_messageInfo_GetShoppingCart.Size(m)
}
func (m *GetShoppingCart) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShoppingCart.DiscardUnknown(m)
}

var xxx_messageInfo_GetShoppingCart proto.InternalMessageInfo

func (m *GetShoppingCart) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type LineItem struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineItem) Reset()         { *m = LineItem{} }
func (m *LineItem) String() string { return proto.CompactTextString(m) }
func (*LineItem) ProtoMessage()    {}
func (*LineItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_230c614558c2d7f8, []int{3}
}

func (m *LineItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineItem.Unmarshal(m, b)
}
func (m *LineItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineItem.Marshal(b, m, deterministic)
}
func (m *LineItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineItem.Merge(m, src)
}
func (m *LineItem) XXX_Size() int {
	return xxx_messageInfo_LineItem.Size(m)
}
func (m *LineItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LineItem.DiscardUnknown(m)
}

var xxx_messageInfo_LineItem proto.InternalMessageInfo

func (m *LineItem) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *LineItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LineItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type Cart struct {
	Items                []*LineItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_230c614558c2d7f8, []int{4}
}

func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (m *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(m, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetItems() []*LineItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*AddLineItem)(nil), "com.example.shoppingcart.AddLineItem")
	proto.RegisterType((*RemoveLineItem)(nil), "com.example.shoppingcart.RemoveLineItem")
	proto.RegisterType((*GetShoppingCart)(nil), "com.example.shoppingcart.GetShoppingCart")
	proto.RegisterType((*LineItem)(nil), "com.example.shoppingcart.LineItem")
	proto.RegisterType((*Cart)(nil), "com.example.shoppingcart.Cart")
}

func init() { proto.RegisterFile("shoppingcart/shoppingcart.proto", fileDescriptor_230c614558c2d7f8) }

var fileDescriptor_230c614558c2d7f8 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xd5, 0x26, 0x69, 0xd3, 0x4e, 0xab, 0x82, 0x56, 0xa2, 0x32, 0x2e, 0x6d, 0xa3, 0x15, 0x48,
	0x29, 0x48, 0x5e, 0x68, 0x2f, 0xc0, 0x89, 0x16, 0xa1, 0x2a, 0x12, 0xe2, 0x60, 0x4e, 0xf4, 0x52,
	0x6d, 0xbc, 0x43, 0x6a, 0x11, 0x7b, 0x8d, 0x3d, 0x46, 0x54, 0x51, 0x0f, 0xf0, 0x03, 0x20, 0xc1,
	0xaf, 0xf0, 0x25, 0xfc, 0x02, 0x1f, 0x82, 0xbc, 0x76, 0xa8, 0x13, 0xb1, 0xe2, 0xc2, 0xcd, 0x9e,
	0x37, 0x3b, 0xef, 0xbd, 0x79, 0x03, 0xfb, 0xc5, 0x85, 0xc9, 0xb2, 0x38, 0x9d, 0x44, 0x2a, 0x27,
	0xd9, 0xfe, 0x09, 0xb2, 0xdc, 0x90, 0xe1, 0x5e, 0x64, 0x92, 0x00, 0x3f, 0xaa, 0x24, 0x9b, 0x62,
	0xd0, 0xc6, 0xfd, 0x9d, 0x89, 0x31, 0x93, 0x29, 0x4a, 0xdb, 0x37, 0x2e, 0xdf, 0x4a, 0x4c, 0x32,
	0xba, 0xac, 0x9f, 0xf9, 0x3b, 0xd1, 0xd4, 0x94, 0xba, 0x20, 0x45, 0x28, 0x31, 0xa5, 0x98, 0x2e,
	0xcf, 0xdf, 0xe1, 0x1c, 0xbc, 0xd3, 0xbc, 0x54, 0x59, 0x2c, 0x55, 0x9a, 0x1a, 0x52, 0x14, 0x9b,
	0xb4, 0x68, 0xd0, 0x5b, 0x2d, 0xf4, 0x82, 0x28, 0xab, 0xcb, 0x62, 0x06, 0x1b, 0xc7, 0x5a, 0xbf,
	0x8c, 0x53, 0x1c, 0x11, 0x26, 0x7c, 0x17, 0xfa, 0x65, 0x81, 0xf9, 0x79, 0xac, 0x3d, 0x36, 0x60,
	0xc3, 0xf5, 0x93, 0xde, 0xd7, 0x1f, 0x1e, 0x0b, 0x57, 0xab, 0xe2, 0x48, 0xf3, 0x5d, 0x80, 0x2c,
	0x37, 0xba, 0x8c, 0xa8, 0xea, 0xe8, 0x54, 0x1d, 0xe1, 0x7a, 0x53, 0x19, 0x69, 0xce, 0xa1, 0x97,
	0xaa, 0x04, 0xbd, 0xae, 0x05, 0xec, 0x37, 0xf7, 0x61, 0xed, 0x7d, 0xa9, 0xac, 0x56, 0xaf, 0x37,
	0x60, 0xc3, 0x95, 0xf0, 0xcf, 0xbf, 0x78, 0x05, 0x5b, 0x21, 0x26, 0xe6, 0x03, 0xfe, 0x1f, 0x7e,
	0xf1, 0x10, 0x6e, 0x9c, 0x22, 0xbd, 0x6e, 0xd6, 0xf9, 0x5c, 0xe5, 0xf4, 0x8f, 0x81, 0xe2, 0x0d,
	0xac, 0xb5, 0xb8, 0xdb, 0xc3, 0x99, 0xcb, 0x5c, 0xc7, 0x61, 0xae, 0xbb, 0x64, 0xee, 0x19, 0xf4,
	0xac, 0x82, 0xc7, 0xb0, 0x12, 0x13, 0x26, 0x85, 0xc7, 0x06, 0xdd, 0xe1, 0xc6, 0xa1, 0x08, 0x5c,
	0xd1, 0x07, 0x73, 0x25, 0x61, 0xfd, 0xe0, 0xf0, 0x7b, 0x17, 0x36, 0x17, 0xcc, 0xa4, 0xd0, 0x3f,
	0xd6, 0xda, 0x8a, 0xbd, 0xe7, 0x1e, 0xd3, 0xca, 0xd3, 0xdf, 0x0e, 0xea, 0xd8, 0x83, 0xf9, 0x39,
	0x05, 0x2f, 0xaa, 0x73, 0x12, 0x77, 0x3f, 0xff, 0xfc, 0xf5, 0xad, 0xb3, 0x27, 0x6e, 0x4b, 0x7b,
	0xa1, 0xb3, 0x66, 0x47, 0x57, 0xd2, 0x32, 0x4b, 0xa5, 0xf5, 0x53, 0x76, 0x9f, 0x7f, 0x62, 0x00,
	0x75, 0x40, 0x96, 0x73, 0xe8, 0xe6, 0x5c, 0x8c, 0xd1, 0x49, 0xfb, 0xc8, 0xd2, 0x3e, 0x10, 0x07,
	0x7f, 0xa7, 0x9d, 0x5d, 0xef, 0xff, 0x4a, 0xe6, 0x76, 0x24, 0xff, 0xc2, 0xa0, 0x7f, 0x8a, 0x64,
	0xfd, 0x1f, 0xb8, 0x05, 0x2c, 0xe5, 0xee, 0xef, 0xb9, 0x5b, 0x2b, 0x5c, 0x3c, 0xb1, 0x4a, 0x8e,
	0xf8, 0x4d, 0xab, 0xa4, 0xb8, 0x96, 0x72, 0xb6, 0xcf, 0xb7, 0x97, 0x6b, 0xb5, 0xbc, 0x71, 0x1d,
	0xcb, 0xc9, 0xd6, 0xd9, 0x66, 0x7b, 0xde, 0x78, 0xd5, 0x9a, 0x3c, 0xfa, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x8c, 0x47, 0xa4, 0x5f, 0xf5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShoppingCartClient is the client API for ShoppingCart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShoppingCartClient interface {
	AddItem(ctx context.Context, in *AddLineItem, opts ...grpc.CallOption) (*empty.Empty, error)
	RemoveItem(ctx context.Context, in *RemoveLineItem, opts ...grpc.CallOption) (*empty.Empty, error)
	GetCart(ctx context.Context, in *GetShoppingCart, opts ...grpc.CallOption) (*Cart, error)
}

type shoppingCartClient struct {
	cc *grpc.ClientConn
}

func NewShoppingCartClient(cc *grpc.ClientConn) ShoppingCartClient {
	return &shoppingCartClient{cc}
}

func (c *shoppingCartClient) AddItem(ctx context.Context, in *AddLineItem, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/com.example.shoppingcart.ShoppingCart/AddItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingCartClient) RemoveItem(ctx context.Context, in *RemoveLineItem, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/com.example.shoppingcart.ShoppingCart/RemoveItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingCartClient) GetCart(ctx context.Context, in *GetShoppingCart, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/com.example.shoppingcart.ShoppingCart/GetCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShoppingCartServer is the server API for ShoppingCart service.
type ShoppingCartServer interface {
	AddItem(context.Context, *AddLineItem) (*empty.Empty, error)
	RemoveItem(context.Context, *RemoveLineItem) (*empty.Empty, error)
	GetCart(context.Context, *GetShoppingCart) (*Cart, error)
}

// UnimplementedShoppingCartServer can be embedded to have forward compatible implementations.
type UnimplementedShoppingCartServer struct {
}

func (*UnimplementedShoppingCartServer) AddItem(ctx context.Context, req *AddLineItem) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItem not implemented")
}
func (*UnimplementedShoppingCartServer) RemoveItem(ctx context.Context, req *RemoveLineItem) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveItem not implemented")
}
func (*UnimplementedShoppingCartServer) GetCart(ctx context.Context, req *GetShoppingCart) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCart not implemented")
}

func RegisterShoppingCartServer(s *grpc.Server, srv ShoppingCartServer) {
	s.RegisterService(&_ShoppingCart_serviceDesc, srv)
}

func _ShoppingCart_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLineItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingCartServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.example.shoppingcart.ShoppingCart/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingCartServer).AddItem(ctx, req.(*AddLineItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingCart_RemoveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLineItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingCartServer).RemoveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.example.shoppingcart.ShoppingCart/RemoveItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingCartServer).RemoveItem(ctx, req.(*RemoveLineItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingCart_GetCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShoppingCart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingCartServer).GetCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.example.shoppingcart.ShoppingCart/GetCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingCartServer).GetCart(ctx, req.(*GetShoppingCart))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShoppingCart_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.example.shoppingcart.ShoppingCart",
	HandlerType: (*ShoppingCartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddItem",
			Handler:    _ShoppingCart_AddItem_Handler,
		},
		{
			MethodName: "RemoveItem",
			Handler:    _ShoppingCart_RemoveItem_Handler,
		},
		{
			MethodName: "GetCart",
			Handler:    _ShoppingCart_GetCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shoppingcart/shoppingcart.proto",
}
